export enum FormaDePago {
  EFECTIVO = 'EFECTIVO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DEPOSITO_EFECTIVO = 'DEPOSITO_EFECTIVO',
  DEPOSITO_CHEQUE = 'DEPOSITO_CHEQUE',
  DEPOSITO_MIXTO = 'DEPOSITO_MIXTO',
  TARJETA_CRE = 'TARJETA_CREDITO',
  TARJETA_DEB = 'TARJETA_DEBITO',
  CHEQUE = 'CHEQUE',
  CHEQUE_PSTF = 'CHEQUE_PSTF',
  NO_DEFINIDO = 'NO_DEFINIDO',
}
